import type { INodeProperties } from 'n8n-workflow';

const showOnlyForOAuth = { resource: ['OAuth'] };

export const oauthDescription: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: showOnlyForOAuth },
    options: [
      { name: 'Open Authorization (Browser)', value: 'open', action: 'Open authorization URL' },
      { name: 'Exchange Code', value: 'exchange', action: 'Exchange authorization code' },
      { name: 'Server-side POST Authorize', value: 'post', action: 'POST authorize' },
    ],
    default: 'open',
  },
  {
    displayName: 'Client ID',
    name: 'clientId',
    type: 'string',
    displayOptions: { show: showOnlyForOAuth },
    placeholder: 'Client ID (if not preconfigured in credentials)',
    description: 'OAuth2 Client Identifier',
    default: '',
  },
  {
    displayName: 'Redirect URI',
    name: 'redirectUri',
    type: 'string',
    displayOptions: { show: showOnlyForOAuth },
    placeholder: 'https://yourapp.example/callback',
    description: 'Redirect URI registered in the OAuth client (required for browser flow)',
    default: '',
  },
  {
    displayName: 'Scope',
    name: 'scope',
    type: 'string',
    displayOptions: { show: showOnlyForOAuth },
    placeholder: 'scopes (space separated)',
    description: 'Optional scopes to request',
    default: '',
  },
  {
    displayName: 'State',
    name: 'state',
    type: 'string',
    displayOptions: { show: showOnlyForOAuth },
    description: 'Optional state parameter for CSRF protection',
    default: '',
  },
  {
    displayName: 'Open Authorization',
    name: 'openAuthorization',
    type: 'boolean',
    displayOptions: { show: { operation: ['open'], resource: ['OAuth'] } },
    default: false,
    description:
      'Trigger to open the authorization URL (GET /api.php/authorize). In UI this should be an action/button that opens a browser window.',
  },
  {
    displayName: 'Authorization Code',
    name: 'authorizationCode',
    type: 'string',
    displayOptions: { show: { operation: ['exchange'], resource: ['OAuth'] } },
    placeholder: 'Code returned after redirect',
    description: 'Paste or capture the authorization code after the redirect',
    default: '',
  },
  {
    displayName: 'Exchange Code',
    name: 'exchangeCode',
    type: 'boolean',
    displayOptions: { show: { operation: ['exchange'], resource: ['OAuth'] } },
    default: false,
    description: 'Trigger to POST to /token to exchange the authorization code for a token',
  },
  {
    displayName: 'POST Authorize (server-side)',
    name: 'postAuthorize',
    type: 'boolean',
    displayOptions: { show: { operation: ['post'], resource: ['OAuth'] } },
    default: false,
    description: 'Trigger to perform server-side POST /api.php/authorize when using non-interactive flow',
  },
  {
    displayName: 'Validate Redirect State',
    name: 'validateState',
    type: 'boolean',
    displayOptions: { show: showOnlyForOAuth },
    default: true,
    description: 'When true, validate that the returned state matches the request',
  },
];
