import type { INodeProperties } from 'n8n-workflow';
import { taskGetManyDescription } from './getAll';
import { taskGetDescription } from './get';
import { taskCreateDescription } from './create';
import { taskUpdateDescription } from './update';
import { taskActionBody } from './actions';

export const taskDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForTasks },
		options: [
			{
				name: 'Add Comment',
				value: 'add_comment',
				action: 'Add a comment to a task',
				description: 'Create a comment on a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/comments' } },
			},
			{
				name: 'Add Manual Work Period',
				value: 'add_manual_work_period',
				action: 'Add manual work period to task',
				description: 'Add manual work period',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/add_manual_work_period' } },
			},
			{
				name: 'Change Board',
				value: 'change_board',
				action: 'Change task board',
				description: 'Change the board of a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/change_board' } },
			},
			{
				name: 'Change Project',
				value: 'change_project',
				action: 'Change task project',
				description: 'Change the project of a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/change_project' } },
			},
			{
				name: 'Change Time Worked',
				value: 'change_time_worked',
				action: 'Change total time worked on task',
				description: 'Change time worked',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/change_time_worked' } },
			},
			{
				name: 'Change Type',
				value: 'change_type',
				action: 'Change task type',
				description: 'Change the type of a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/change_type' } },
			},
			{
				name: 'Clone',
				value: 'clone',
				action: 'Clone a task',
				description: 'Clone an existing task',
				routing: { request: { method: 'POST', url: '/tasks/clone' } },
			},
			{
				name: 'Complete Workflow Step',
				value: 'complete_workflow_step',
				action: 'Complete a workflow step',
				description: 'Complete a workflow step for the task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/complete_workflow_step' } },
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a task',
				description: 'Create a new task',
				routing: { request: { method: 'POST', url: '/tasks' } },
			},
			{
				name: 'Create Assignments',
				value: 'create_assignments',
				action: 'Create assignment for another user',
				description: 'Create assignments for the task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/create_assignments' } },
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a task',
				description: 'Delete a task',
				routing: { request: { method: 'DELETE', url: '=/tasks/{{$parameter.taskId}}' } },
			},
			{
				name: 'Deliver',
				value: 'deliver',
				action: 'Deliver a task',
				description: 'Move task to delivered/closed state',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/deliver' } },
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a task',
				description: 'Get a single task',
				routing: { request: { method: 'GET', url: '=/tasks/{{$parameter.taskId}}' } },
			},
			{
				name: 'Get Fields',
				value: 'get_fields',
				action: 'Get fields of a task board',
				description: "List fields from task's board",
				routing: { request: { method: 'GET', url: '=/tasks/{{$parameter.taskId}}/fields' } },
			},
			{
				name: 'Get Form Answers',
				value: 'get_form_answers',
				action: 'Get form answers for a task',
				description: 'Retrieve form answers that created the task',
				routing: { request: { method: 'GET', url: '=/tasks/{{$parameter.taskId}}/form_answers' } },
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many tasks',
				description: 'Get many tasks',
				routing: { request: { method: 'GET', url: '/tasks' } },
			},
			{
				name: 'Get Subtasks',
				value: 'get_subtasks',
				action: 'Get subtasks of a task',
				description: 'List subtasks for a task',
				routing: { request: { method: 'GET', url: '=/tasks/{{$parameter.taskId}}/subtasks' } },
			},
			{
				name: 'Mark As Urgent',
				value: 'mark_as_urgent',
				action: 'Mark task as urgent',
				description: 'Mark the task as urgent',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/mark_as_urgent' } },
			},
			{
				name: 'Move',
				value: 'move',
				action: 'Move a task between stages',
				description: 'Move task between stages',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/move' } },
			},
			{
				name: 'Move To Next Stage',
				value: 'move_to_next_stage',
				action: 'Move task to next stage',
				description: 'Advance the task to the next stage',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/move_to_next_stage' } },
			},
			{
				name: 'Move To Top',
				value: 'move_to_top',
				action: 'Move task to top',
				description: 'Move the task to the top of the list',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/move_to_top' } },
			},
			{
				name: 'Pause',
				value: 'pause',
				action: 'Pause a task',
				description: 'Pause a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/pause' } },
			},
			{
				name: 'Play',
				value: 'play',
				action: 'Play a task',
				description: 'Create assignment and play a task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/play' } },
			},
			{
				name: 'Reestimate',
				value: 'reestimate',
				action: 'Reestimate a task',
				description: 'Change task estimation/points',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/reestimate' } },
			},
			{
				name: 'Reopen',
				value: 'reopen',
				action: 'Reopen a task',
				description: 'Reopen a closed task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/reopen' } },
			},
			{
				name: 'Reposition',
				value: 'reposition',
				action: 'Reposition a task',
				description: 'Reposition a task within a stage',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/reposition' } },
			},
			{
				name: 'Share',
				value: 'share',
				action: 'Share a task',
				description: 'Share the task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/share' } },
			},
			{
				name: 'Undo Workflow Step',
				value: 'undo_workflow_step',
				action: 'Undo a workflow step',
				description: 'Undo a workflow step for the task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/undo_workflow_step' } },
			},
			{
				name: 'Unmark As Urgent',
				value: 'unmark_as_urgent',
				action: 'Unmark task as urgent',
				description: 'Remove urgent mark from task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/unmark_as_urgent' } },
			},
			{
				name: 'Unshare',
				value: 'unshare',
				action: 'Unshare a task',
				description: 'Unshare the task',
				routing: { request: { method: 'POST', url: '=/tasks/{{$parameter.taskId}}/unshare' } },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a task',
				description: 'Update task fields',
				routing: { request: { method: 'PUT', url: '=/tasks/{{$parameter.taskId}}' } },
			},
			{
				name: 'Update Comment',
				value: 'update_comment',
				action: 'Update a comment on a task',
				description: 'Update a task comment',
				routing: { request: { method: 'PUT', url: '=/tasks/{{$parameter.taskId}}/comments/{{$parameter.commentId}}' } },
			},
		],
		default: 'getAll',
	},
	...taskGetManyDescription,
	...taskGetDescription,
	...taskCreateDescription,
	...taskUpdateDescription,
	...taskActionBody,
];
