import type { INodeProperties } from 'n8n-workflow';

const showOnlyForProjects = {
  resource: ['projects'],
};

export const projectsDescription: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: showOnlyForProjects },
    options: [
      {
        name: 'List Projects',
        value: 'getAll',
        action: 'Get many projects',
        description: 'List projects',
        routing: { request: { method: 'GET', url: '/projects' } },
      },
      {
        name: 'Get',
        value: 'get',
        action: 'Get a project',
        description: 'Get a single project by id',
        routing: { request: { method: 'GET', url: '=/projects/{{$parameter.projectId}}' } },
      },
      {
        name: 'Create',
        value: 'create',
        action: 'Create a project',
        description: 'Create a new project',
        routing: { request: { method: 'POST', url: '/projects' } },
      },
      {
        name: 'Update',
        value: 'update',
        action: 'Update a project',
        description: 'Update project fields (deliver/reopen)',
        routing: { request: { method: 'PUT', url: '=/projects/{{$parameter.projectId}}' } },
      },
      {
        name: 'Related Users',
        value: 'related_users',
        action: 'List users related in a project',
        description: 'List users related in a project (responsible, owners, followers)',
        routing: { request: { method: 'GET', url: '=/projects/{{$parameter.projectId}}/related_users' } },
      },
      {
        name: 'Move',
        value: 'move',
        action: 'Move project',
        description: 'Move project to another client/group/subgroup',
        routing: { request: { method: 'POST', url: '=/projects/{{$parameter.projectId}}/move' } },
      },
      {
        name: 'Share',
        value: 'share',
        action: 'Share the project',
        description: 'Share the project with guests',
        routing: { request: { method: 'POST', url: '=/projects/{{$parameter.projectId}}/share' } },
      },
      {
        name: 'Unshare',
        value: 'unshare',
        action: 'Unshare the project',
        description: 'Unshare the project',
        routing: { request: { method: 'POST', url: '=/projects/{{$parameter.projectId}}/unshare' } },
      },
      {
        name: 'Clone',
        value: 'clone',
        action: 'Clone a project',
        description: 'Clone a project',
        routing: { request: { method: 'POST', url: '=/projects/{{$parameter.projectId}}/clone' } },
      },
      {
        name: 'Change Board Stage',
        value: 'change_board_stage',
        action: 'Change project board stage',
        description: 'Change a project board stage',
        routing: { request: { method: 'POST', url: '=/projects/{{$parameter.projectId}}/change_board_stage' } },
      },
      {
        name: 'List Filters',
        value: 'getAll_filters',
        action: 'List project filters',
        description: 'List all project filters the current user can view',
        routing: { request: { method: 'GET', url: '/projects/filters' } },
      },
      {
        name: 'Get Filter',
        value: 'get_filter',
        action: 'Get a project filter',
        description: 'Get a single project filter by id',
        routing: { request: { method: 'GET', url: '=/projects/filters/{{$parameter.filterId}}' } },
      },
      {
        name: 'Delete Filter',
        value: 'delete_filter',
        action: 'Delete a project filter',
        description: 'Delete a filter record',
        routing: { request: { method: 'DELETE', url: '=/projects/filters/{{$parameter.filterId}}' } },
      },
    ],
    default: 'getAll_filters',
  },
  {
    displayName: 'Project ID',
    name: 'projectId',
    type: 'string',
    displayOptions: { show: { resource: ['projects'], operation: ['get', 'update', 'related_users', 'move', 'share', 'unshare', 'clone', 'change_board_stage'] } },
    default: '',
    description: 'ID of the project',
  },
  {
    displayName: 'Project Object (JSON)',
    name: 'projectObject',
    type: 'json',
    displayOptions: { show: { resource: ['projects'], operation: ['create', 'update'] } },
    default: '{}',
    description: 'Project payload, e.g. {"project": {"name":"New"}}',
    routing: { send: { type: 'body', property: 'project' } },
  },
  {
    displayName: 'Move Object (JSON)',
    name: 'moveObject',
    type: 'json',
    displayOptions: { show: { resource: ['projects'], operation: ['move'] } },
    default: '{}',
    description: 'Move payload, e.g. {"client_id":2} or {"project_group_id":4}',
  },
  {
    displayName: 'Share Object (JSON)',
    name: 'shareObject',
    type: 'json',
    displayOptions: { show: { resource: ['projects'], operation: ['share'] } },
    default: '{}',
    description: 'Share payload, e.g. {"sharing_details":["desired_date"],"guests_params":[{"email":"a@b.com"}] }',
  },
  {
    displayName: 'Clone Object (JSON)',
    name: 'cloneObject',
    type: 'json',
    displayOptions: { show: { resource: ['projects'], operation: ['clone'] } },
    default: '{}',
    description: 'Clone payload, e.g. {"new_project":{"name":"Cloned"}}',
  },
  {
    displayName: 'Change Board Stage Object (JSON)',
    name: 'changeBoardStageObject',
    type: 'json',
    displayOptions: { show: { resource: ['projects'], operation: ['change_board_stage'] } },
    default: '{}',
    description: 'Payload, e.g. {"board_stage_id":1}',
  },
  {
    displayName: 'Filter ID',
    name: 'filterId',
    type: 'string',
    displayOptions: { show: { resource: ['projects'], operation: ['get_filter', 'delete_filter'] } },
    default: '',
    description: 'ID of the project filter',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: { show: { resource: ['projects'], operation: ['getAll_filters'], returnAll: [false] } },
    typeOptions: { minValue: 1, maxValue: 100 },
    default: 50,
    routing: { send: { type: 'query', property: 'limit' }, output: { maxResults: '={{$value}}' } },
    description: 'Max number of results to return',
  },
  {
    displayName: 'Page',
    name: 'page',
    type: 'number',
    displayOptions: { show: { resource: ['projects'], operation: ['getAll_filters'], returnAll: [false] } },
    default: 1,
    description: 'Page number for pagination (1-based)',
    routing: { send: { type: 'query', property: 'page' } },
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: { show: { resource: ['projects'], operation: ['getAll_filters'] } },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
    routing: { send: { paginate: '={{ $value }}' }, operations: { pagination: { type: 'offset', properties: { limitParameter: 'limit', offsetParameter: 'offset', pageSize: 100, type: 'query' } } } },
  },
];
